
export const MOCK_COURSES = [
  {
    _id: "mock-1",
    title: "Complete Web Development Bootcamp",
    tagline: "Become a full-stack developer",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    description: "Learn web development from scratch. HTML, CSS, Javascript, React, Node.",
    main_contributor: {
        _id: "contributor-1",
        name: "John Doe",
        nickname: "JD",
        image: "https://api.dicebear.com/7.x/avataaars/svg?seed=John"
    },
    other_contributor: [],
    amount: 19999,
    level: "beginner",
    language: "English",
    tags: ["web", "development", "coding"],
    rating: 4.8,
    duration: 45,
    lessons: [],
    enrolled_count: 1250,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "mock-2",
    title: "Advanced React Patterns",
    tagline: "Master React.js",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee",
    description: "Take your React skills to the next level with advanced patterns and performance optimization.",
    main_contributor: {
        _id: "contributor-2",
        name: "Jane Smith",
        nickname: "JS",
        image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane"
    },
    other_contributor: [],
    amount: 25000,
    level: "advanced",
    language: "English",
    tags: ["react", "frontend"],
    rating: 4.9,
    duration: 12,
    lessons: [],
    enrolled_count: 850,
     createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "mock-3",
    title: "UI/UX Design Fundamentals",
    tagline: "Design beautiful interfaces",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5",
    description: "Learn the principles of UI/UX design and how to create user-friendly interfaces.",
    main_contributor: {
        _id: "contributor-3",
        name: "Alex Johnson",
        nickname: "AJ",
        image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex"
    },
    other_contributor: [],
    amount: 15000,
    level: "beginner",
    language: "English",
    tags: ["design", "ui/ux"],
    rating: 4.7,
    duration: 20,
    lessons: [],
    enrolled_count: 2100,
     createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "mock-4",
    title: "Python for Data Science",
    tagline: "Analyze data with Python",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5",
    description: "Master Python programming for data analysis and visualization.",
    main_contributor: {
        _id: "contributor-4",
        name: "Sarah Lee",
        nickname: "SL",
        image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah"
    },
    other_contributor: [],
    amount: 22000,
    level: "intermediate",
    language: "English",
    tags: ["python", "data science"],
    rating: 4.6,
    duration: 35,
    lessons: [],
    enrolled_count: 1500,
     createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
